// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.17379
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UCosmic.Www.Mvc.Areas.RecruitmentAgencies.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class RA_US_0003_ConfigureRecruitmentAgencyModuleWelcomeMessageFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "RA_US_0003.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "RA_US_0003 - Configure Recruitment Agency Module Welcome Message", @"In order to communicate specific details about my institution's recruitment agency application and approval process
As a recrutiment agency supervisor
I want to configure a custom message to be displayed to recruitment agency applicants before they begin the online application", ProgrammingLanguage.CSharp, new string[] {
                        "RepsModule"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "RA_US_0003 - Configure Recruitment Agency Module Welcome Message")))
            {
                UCosmic.Www.Mvc.Areas.RecruitmentAgencies.Features.RA_US_0003_ConfigureRecruitmentAgencyModuleWelcomeMessageFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void RecruitmentAgencyModuleWelcomeMessageBasicEdit(string browserName, string userEmail, string establishmentId, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Recruitment Agency Module Welcome Message Basic Edit", exampleTags);
#line 12
this.ScenarioSetup(scenarioInfo);
#line 15
    testRunner.Given(string.Format("I am using the {0} browser", browserName));
#line 18
    testRunner.When(string.Format("I sign in as \"{0}\" with password \"asdfasdf\"", userEmail));
#line 19
    testRunner.And(string.Format("I browse to the \"{0}/recruitment-agencies/configure/welcome-message\" url", establishmentId));
#line 20
    testRunner.Then("I should see a \"Status\" field with \"enabled\" and \"disabled\" radio buttons");
#line 21
    testRunner.And("I should see a \"Title\" field with textarea");
#line 22
    testRunner.And("I should see a \"Content\" field with TinyMCE editor");
#line 23
    testRunner.And("I should see radio buttons for \"Active message\" and \"Draft message\"");
#line 24
    testRunner.And("I should see a \"Save Draft\" button");
#line 25
    testRunner.And("I should see a \"Save & Activate\" button");
#line 26
    testRunner.And("I should see a \"Discard & Cancel\" link");
#line 29
    testRunner.When("I click the \"enabled\" radio button for the \"Status\" field");
#line 30
    testRunner.And("I type \"Here is a sample heading\" into the \"Title\" field");
#line 31
    testRunner.And("I type \"Here is sample content\" into the \"Content\" field");
#line 32
    testRunner.And("I click the \"Save & Activate\" button");
#line 33
    testRunner.Then(string.Format("I should see a page at the \"{0}/recruitment-agencies/configure\" url", establishmentId));
#line 34
    testRunner.And("I should see a temporary \"Your Recruitment Agency Application Welcome Message has" +
                    " been saved\" feedback message");
#line 37
    testRunner.When(string.Format("I browse to the \"{0}/recruitment-agencies/configure/welcome-message\" url", establishmentId));
#line 38
    testRunner.Then("I should see the \"enabled\" radio button for the \"Status\" field is checked");
#line 39
    testRunner.And("I should see \"Here is a sample heading\" in the \"Title\" field");
#line 40
    testRunner.And("I should see \"Here is sample content\" in the \"Content\" field");
#line 41
    testRunner.And("I should see the \"Active message\" radio button is checked");
#line 44
    testRunner.When("I type \"Here is sample content that I have edited\" into the \"Content\" field");
#line 45
    testRunner.Then("I should see the \"Draft message\" radio button is checked");
#line 48
    testRunner.When("I click the \"Active message\" radio button");
#line 49
    testRunner.Then("I should see \"Here is sample content\" in the \"Content\" field");
#line 51
    testRunner.When("I click the \"Draft message\" radio button");
#line 52
    testRunner.Then("I should see \"Here is sample content that I have edited\" in the \"Content\" field");
#line 55
    testRunner.When("I click the \"Save Draft\" button");
#line 56
    testRunner.Then(string.Format("I should see a page at the \"{0}/recruitment-agencies/configure/welcome-message\" u" +
                        "rl", establishmentId));
#line 57
    testRunner.And("I should see a temporary \"Your Welcome Message draft has been saved\" feedback mes" +
                    "sage");
#line 60
    testRunner.When(string.Format("I browse to the \"{0}/recruitment-agencies/configure/welcome-message\" url", establishmentId));
#line 61
    testRunner.And("I click the \"disabled\" radio button for the \"Status\" field");
#line 62
    testRunner.Then("I should see a dialog confirming that I want to disable the welcome message");
#line 65
    testRunner.When("I click to cancel the disabling of the welcome message");
#line 66
    testRunner.Then("I should see the \"enabled\" radio button for the \"Status\" field is checked");
#line 69
    testRunner.When("I click the \"disabled\" radio button for the \"Status\" field");
#line 70
    testRunner.And("I see a dialog confirming that I want to disable the welcome message");
#line 71
    testRunner.And("I click to accept the disabling of the welcome message");
#line 72
    testRunner.Then("I should see the \"disabled\" radio button for the \"Status\" field is checked");
#line 75
    testRunner.When("I type \"Here is a sample heading that I have edited\" into the \"Title\" field");
#line 76
    testRunner.And("I click the \"Save & Activate\" button");
#line 77
    testRunner.Then(string.Format("I should see a page at the \"{0}/recruitment-agencies/configure\" url", establishmentId));
#line 78
    testRunner.And("I should see a temporary \"Your Recruitment Agency Application Welcome Message has" +
                    " been saved\" feedback message");
#line 81
    testRunner.When(string.Format("I browse to the \"{0}/recruitment-agencies/configure/welcome-message\" url", establishmentId));
#line 82
    testRunner.Then("I should see the \"disabled\" radio button for the \"Status\" field is checked");
#line 83
    testRunner.And("I should see \"Here is a sample heading that I have edited\" in the \"Title\" field");
#line 84
    testRunner.And("I should see \"Here is sample content that I have edited\" in the \"Content\" field");
#line 85
    testRunner.And("I should see the \"Active message\" radio button is checked");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Recruitment Agency Module Welcome Message Basic Edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "RA_US_0003 - Configure Recruitment Agency Module Welcome Message")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("RepsModule")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Chrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BrowserName", "Chrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserEmail", "supervisor1@uc.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:EstablishmentId", "www.uc.edu")]
        public virtual void RecruitmentAgencyModuleWelcomeMessageBasicEdit_Chrome()
        {
            this.RecruitmentAgencyModuleWelcomeMessageBasicEdit("Chrome", "supervisor1@uc.edu", "www.uc.edu", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Recruitment Agency Module Welcome Message Basic Edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "RA_US_0003 - Configure Recruitment Agency Module Welcome Message")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("RepsModule")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Firefox")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BrowserName", "Firefox")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserEmail", "supervisor1@suny.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:EstablishmentId", "www.suny.edu")]
        public virtual void RecruitmentAgencyModuleWelcomeMessageBasicEdit_Firefox()
        {
            this.RecruitmentAgencyModuleWelcomeMessageBasicEdit("Firefox", "supervisor1@suny.edu", "www.suny.edu", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Recruitment Agency Module Welcome Message Basic Edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "RA_US_0003 - Configure Recruitment Agency Module Welcome Message")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("RepsModule")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Internet Explorer")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BrowserName", "Internet Explorer")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserEmail", "supervisor1@napier.ac.uk")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:EstablishmentId", "www.napier.ac.uk")]
        public virtual void RecruitmentAgencyModuleWelcomeMessageBasicEdit_InternetExplorer()
        {
            this.RecruitmentAgencyModuleWelcomeMessageBasicEdit("Internet Explorer", "supervisor1@napier.ac.uk", "www.napier.ac.uk", ((string[])(null)));
        }
    }
}
#pragma warning restore
#endregion
