// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.17379
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UCosmic.Www.Mvc.Areas.InstitutionalAgreements
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class InstitutionalAgreementManagementPreviewRevision2Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ManagementFormsR02.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Institutional Agreement Management Preview Revision 2", "  In order to have centralized online access to documents relating to my Institut" +
                    "ional Agreements\r\n  As an Institutional Agreement Manager\r\n  I want to upload, r" +
                    "emove, and generally manage which files are attached to my Institutional Agreeme" +
                    "nts in UCosmic", ProgrammingLanguage.CSharp, new string[] {
                        "InstAgrForms",
                        "InstAgrFormsR02"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Institutional Agreement Management Preview Revision 2")))
            {
                UCosmic.Www.Mvc.Areas.InstitutionalAgreements.InstitutionalAgreementManagementPreviewRevision2Feature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 8
#line 9
    testRunner.Given("I am signed in as manager1@uc.edu");
#line 10
    testRunner.And("I am starting from the Institutional Agreement Management page");
#line hidden
        }
        
        public virtual void FileUploadInputFieldIsDisplayedInTheFileAttachmentsFieldset(string addOrEdit, string linkText, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "InstAgrFormsR0201"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("File upload input field is displayed in the File Attachments fieldset", @__tags);
#line 13
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 15
    testRunner.When(string.Format("I click the \"{0}\" link", linkText));
#line 16
    testRunner.Then(string.Format("I should see the Institutional Agreement {0} page", addOrEdit));
#line 17
    testRunner.And("I should see a File Attachments upload field");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("File upload input field is displayed in the File Attachments fieldset")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0201")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Add")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Add")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Add a new agreement")]
        public virtual void FileUploadInputFieldIsDisplayedInTheFileAttachmentsFieldset_Add()
        {
            this.FileUploadInputFieldIsDisplayedInTheFileAttachmentsFieldset("Add", "Add a new agreement", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("File upload input field is displayed in the File Attachments fieldset")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0201")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Agreement, UC 01 test")]
        public virtual void FileUploadInputFieldIsDisplayedInTheFileAttachmentsFieldset_Edit()
        {
            this.FileUploadInputFieldIsDisplayedInTheFileAttachmentsFieldset("Edit", "Agreement, UC 01 test", ((string[])(null)));
        }
        
        public virtual void AddFileAttachmentFailsForInvalidFileTypes(string addOrEdit, string linkText, string filePath, string fileName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "InstAgrFormsR0202",
                    "NotInChrome"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add file attachment fails for invalid file types", @__tags);
#line 25
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 27
    testRunner.When(string.Format("I click the \"{0}\" link", linkText));
#line 28
    testRunner.Then(string.Format("I should see the Institutional Agreement {0} page", addOrEdit));
#line 29
    testRunner.And("I should see a File Attachments upload field");
#line 31
    testRunner.When(string.Format("I choose the file \"{0}\" for the File Attachments upload field", filePath));
#line 32
    testRunner.Then(string.Format("I should not see an item for \"{0}\" in the File Attachments list", fileName));
#line 33
    testRunner.And("I should see the Invalid error message for the File Attachments field");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment fails for invalid file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0202")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Add")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Add a new agreement")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\JavaScriptFile1.js")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "JavaScriptFile1.js")]
        public virtual void AddFileAttachmentFailsForInvalidFileTypes_Variant0()
        {
            this.AddFileAttachmentFailsForInvalidFileTypes("Add", "Add a new agreement", "C:\\WebDriverFileUploads\\JavaScriptFile1.js", "JavaScriptFile1.js", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment fails for invalid file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0202")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Add")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Add a new agreement")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\VbScriptFile1.vb")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "VbScriptFile1.vb")]
        public virtual void AddFileAttachmentFailsForInvalidFileTypes_Variant1()
        {
            this.AddFileAttachmentFailsForInvalidFileTypes("Add", "Add a new agreement", "C:\\WebDriverFileUploads\\VbScriptFile1.vb", "VbScriptFile1.vb", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment fails for invalid file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0202")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Add")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Add a new agreement")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\ExtensionlessFile1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "ExtensionlessFile1")]
        public virtual void AddFileAttachmentFailsForInvalidFileTypes_Variant2()
        {
            this.AddFileAttachmentFailsForInvalidFileTypes("Add", "Add a new agreement", "C:\\WebDriverFileUploads\\ExtensionlessFile1", "ExtensionlessFile1", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment fails for invalid file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0202")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Agreement, UC 01 test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\JavaScriptFile1.js")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "JavaScriptFile1.js")]
        public virtual void AddFileAttachmentFailsForInvalidFileTypes_Variant3()
        {
            this.AddFileAttachmentFailsForInvalidFileTypes("Edit", "Agreement, UC 01 test", "C:\\WebDriverFileUploads\\JavaScriptFile1.js", "JavaScriptFile1.js", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment fails for invalid file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0202")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Agreement, UC 01 test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\VbScriptFile1.vb")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "VbScriptFile1.vb")]
        public virtual void AddFileAttachmentFailsForInvalidFileTypes_Variant4()
        {
            this.AddFileAttachmentFailsForInvalidFileTypes("Edit", "Agreement, UC 01 test", "C:\\WebDriverFileUploads\\VbScriptFile1.vb", "VbScriptFile1.vb", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment fails for invalid file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0202")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Agreement, UC 01 test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\ExtensionlessFile1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "ExtensionlessFile1")]
        public virtual void AddFileAttachmentFailsForInvalidFileTypes_Variant5()
        {
            this.AddFileAttachmentFailsForInvalidFileTypes("Edit", "Agreement, UC 01 test", "C:\\WebDriverFileUploads\\ExtensionlessFile1", "ExtensionlessFile1", ((string[])(null)));
        }
        
        public virtual void AddFileAttachmentSucceedsForAllowedFileTypes(string addOrEdit, string linkText, string filePath, string fileName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "InstAgrFormsR0203",
                    "NotInChrome"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add file attachment succeeds for allowed file types", @__tags);
#line 45
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 47
    testRunner.When(string.Format("I click the \"{0}\" link", linkText));
#line 48
    testRunner.Then(string.Format("I should see the Institutional Agreement {0} page", addOrEdit));
#line 49
    testRunner.And("I should see a File Attachments upload field");
#line 51
    testRunner.When(string.Format("I choose the file \"{0}\" for the File Attachments upload field", filePath));
#line 52
    testRunner.Then(string.Format("I should see an item for \"{0}\" in the File Attachments list", fileName));
#line 53
    testRunner.And("I should not see the Invalid error message for the File Attachments field");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment succeeds for allowed file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0203")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Add")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Add a new agreement")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\SpecFlow Guide.pdf")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "SpecFlow Guide.pdf")]
        public virtual void AddFileAttachmentSucceedsForAllowedFileTypes_Variant0()
        {
            this.AddFileAttachmentSucceedsForAllowedFileTypes("Add", "Add a new agreement", "C:\\WebDriverFileUploads\\SpecFlow Guide.pdf", "SpecFlow Guide.pdf", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment succeeds for allowed file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0203")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Add")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Add a new agreement")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\WordDocument1.doc")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "WordDocument1.doc")]
        public virtual void AddFileAttachmentSucceedsForAllowedFileTypes_Variant1()
        {
            this.AddFileAttachmentSucceedsForAllowedFileTypes("Add", "Add a new agreement", "C:\\WebDriverFileUploads\\WordDocument1.doc", "WordDocument1.doc", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment succeeds for allowed file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0203")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Add")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Add a new agreement")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\WordDocument1.docx")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "WordDocument1.docx")]
        public virtual void AddFileAttachmentSucceedsForAllowedFileTypes_Variant2()
        {
            this.AddFileAttachmentSucceedsForAllowedFileTypes("Add", "Add a new agreement", "C:\\WebDriverFileUploads\\WordDocument1.docx", "WordDocument1.docx", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment succeeds for allowed file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0203")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Add")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Add a new agreement")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\OpenDocument1.odt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "OpenDocument1.odt")]
        public virtual void AddFileAttachmentSucceedsForAllowedFileTypes_Variant3()
        {
            this.AddFileAttachmentSucceedsForAllowedFileTypes("Add", "Add a new agreement", "C:\\WebDriverFileUploads\\OpenDocument1.odt", "OpenDocument1.odt", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment succeeds for allowed file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0203")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Add")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Add a new agreement")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\ExcelWorkbook1.xls")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "ExcelWorkbook1.xls")]
        public virtual void AddFileAttachmentSucceedsForAllowedFileTypes_Variant4()
        {
            this.AddFileAttachmentSucceedsForAllowedFileTypes("Add", "Add a new agreement", "C:\\WebDriverFileUploads\\ExcelWorkbook1.xls", "ExcelWorkbook1.xls", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment succeeds for allowed file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0203")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Add")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Add a new agreement")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\ExcelWorkbook1.xlsx")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "ExcelWorkbook1.xlsx")]
        public virtual void AddFileAttachmentSucceedsForAllowedFileTypes_Variant5()
        {
            this.AddFileAttachmentSucceedsForAllowedFileTypes("Add", "Add a new agreement", "C:\\WebDriverFileUploads\\ExcelWorkbook1.xlsx", "ExcelWorkbook1.xlsx", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment succeeds for allowed file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0203")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Add")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Add a new agreement")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\OpenSpreadsheet1.ods")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "OpenSpreadsheet1.ods")]
        public virtual void AddFileAttachmentSucceedsForAllowedFileTypes_Variant6()
        {
            this.AddFileAttachmentSucceedsForAllowedFileTypes("Add", "Add a new agreement", "C:\\WebDriverFileUploads\\OpenSpreadsheet1.ods", "OpenSpreadsheet1.ods", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment succeeds for allowed file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0203")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 7")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Add")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Add a new agreement")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\PowerPoint1.ppt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "PowerPoint1.ppt")]
        public virtual void AddFileAttachmentSucceedsForAllowedFileTypes_Variant7()
        {
            this.AddFileAttachmentSucceedsForAllowedFileTypes("Add", "Add a new agreement", "C:\\WebDriverFileUploads\\PowerPoint1.ppt", "PowerPoint1.ppt", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment succeeds for allowed file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0203")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Add")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Add a new agreement")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\PowerPoint1.pptx")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "PowerPoint1.pptx")]
        public virtual void AddFileAttachmentSucceedsForAllowedFileTypes_Variant8()
        {
            this.AddFileAttachmentSucceedsForAllowedFileTypes("Add", "Add a new agreement", "C:\\WebDriverFileUploads\\PowerPoint1.pptx", "PowerPoint1.pptx", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment succeeds for allowed file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0203")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 9")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Agreement, UC 01 test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\SpecFlow Guide.pdf")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "SpecFlow Guide.pdf")]
        public virtual void AddFileAttachmentSucceedsForAllowedFileTypes_Variant9()
        {
            this.AddFileAttachmentSucceedsForAllowedFileTypes("Edit", "Agreement, UC 01 test", "C:\\WebDriverFileUploads\\SpecFlow Guide.pdf", "SpecFlow Guide.pdf", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment succeeds for allowed file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0203")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 10")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Agreement, UC 01 test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\WordDocument1.doc")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "WordDocument1.doc")]
        public virtual void AddFileAttachmentSucceedsForAllowedFileTypes_Variant10()
        {
            this.AddFileAttachmentSucceedsForAllowedFileTypes("Edit", "Agreement, UC 01 test", "C:\\WebDriverFileUploads\\WordDocument1.doc", "WordDocument1.doc", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment succeeds for allowed file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0203")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 11")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Agreement, UC 01 test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\WordDocument1.docx")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "WordDocument1.docx")]
        public virtual void AddFileAttachmentSucceedsForAllowedFileTypes_Variant11()
        {
            this.AddFileAttachmentSucceedsForAllowedFileTypes("Edit", "Agreement, UC 01 test", "C:\\WebDriverFileUploads\\WordDocument1.docx", "WordDocument1.docx", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment succeeds for allowed file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0203")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 12")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Agreement, UC 01 test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\OpenDocument1.odt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "OpenDocument1.odt")]
        public virtual void AddFileAttachmentSucceedsForAllowedFileTypes_Variant12()
        {
            this.AddFileAttachmentSucceedsForAllowedFileTypes("Edit", "Agreement, UC 01 test", "C:\\WebDriverFileUploads\\OpenDocument1.odt", "OpenDocument1.odt", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment succeeds for allowed file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0203")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 13")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Agreement, UC 01 test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\ExcelWorkbook1.xls")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "ExcelWorkbook1.xls")]
        public virtual void AddFileAttachmentSucceedsForAllowedFileTypes_Variant13()
        {
            this.AddFileAttachmentSucceedsForAllowedFileTypes("Edit", "Agreement, UC 01 test", "C:\\WebDriverFileUploads\\ExcelWorkbook1.xls", "ExcelWorkbook1.xls", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment succeeds for allowed file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0203")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 14")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Agreement, UC 01 test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\ExcelWorkbook1.xlsx")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "ExcelWorkbook1.xlsx")]
        public virtual void AddFileAttachmentSucceedsForAllowedFileTypes_Variant14()
        {
            this.AddFileAttachmentSucceedsForAllowedFileTypes("Edit", "Agreement, UC 01 test", "C:\\WebDriverFileUploads\\ExcelWorkbook1.xlsx", "ExcelWorkbook1.xlsx", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment succeeds for allowed file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0203")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 15")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Agreement, UC 01 test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\OpenSpreadsheet1.ods")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "OpenSpreadsheet1.ods")]
        public virtual void AddFileAttachmentSucceedsForAllowedFileTypes_Variant15()
        {
            this.AddFileAttachmentSucceedsForAllowedFileTypes("Edit", "Agreement, UC 01 test", "C:\\WebDriverFileUploads\\OpenSpreadsheet1.ods", "OpenSpreadsheet1.ods", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment succeeds for allowed file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0203")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 16")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Agreement, UC 01 test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\PowerPoint1.ppt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "PowerPoint1.ppt")]
        public virtual void AddFileAttachmentSucceedsForAllowedFileTypes_Variant16()
        {
            this.AddFileAttachmentSucceedsForAllowedFileTypes("Edit", "Agreement, UC 01 test", "C:\\WebDriverFileUploads\\PowerPoint1.ppt", "PowerPoint1.ppt", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Add file attachment succeeds for allowed file types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0203")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 17")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Agreement, UC 01 test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\PowerPoint1.pptx")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "PowerPoint1.pptx")]
        public virtual void AddFileAttachmentSucceedsForAllowedFileTypes_Variant17()
        {
            this.AddFileAttachmentSucceedsForAllowedFileTypes("Edit", "Agreement, UC 01 test", "C:\\WebDriverFileUploads\\PowerPoint1.pptx", "PowerPoint1.pptx", ((string[])(null)));
        }
        
        public virtual void RemoveFileAttachmentFromListSucceeds(string addOrEdit, string linkText, string filePath, string fileName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "InstAgrFormsR0204",
                    "NotInChrome"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Remove file attachment from list succeeds", @__tags);
#line 77
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 79
    testRunner.When(string.Format("I click the \"{0}\" link", linkText));
#line 80
    testRunner.Then(string.Format("I should see the Institutional Agreement {0} page", addOrEdit));
#line 81
    testRunner.And("I should see a File Attachments upload field");
#line 83
    testRunner.When(string.Format("I choose the file \"{0}\" for the File Attachments upload field", filePath));
#line 84
    testRunner.Then(string.Format("I should see an item for \"{0}\" in the File Attachments list", fileName));
#line 85
    testRunner.And("I should not see the Invalid error message for the File Attachments field");
#line 87
    testRunner.When(string.Format("I click the remove icon for \"{0}\" in the File Attachments list", fileName));
#line 88
    testRunner.Then(string.Format("I should not see an item for \"{0}\" in the File Attachments list", fileName));
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Remove file attachment from list succeeds")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0204")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Add")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Add")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Add a new agreement")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\LargePdf33.8.pdf")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "LargePdf33.8.pdf")]
        public virtual void RemoveFileAttachmentFromListSucceeds_Add()
        {
            this.RemoveFileAttachmentFromListSucceeds("Add", "Add a new agreement", "C:\\WebDriverFileUploads\\LargePdf33.8.pdf", "LargePdf33.8.pdf", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Remove file attachment from list succeeds")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0204")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "Edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Agreement, UC 01 test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\LargePdf33.8.pdf")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "LargePdf33.8.pdf")]
        public virtual void RemoveFileAttachmentFromListSucceeds_Edit()
        {
            this.RemoveFileAttachmentFromListSucceeds("Edit", "Agreement, UC 01 test", "C:\\WebDriverFileUploads\\LargePdf33.8.pdf", "LargePdf33.8.pdf", ((string[])(null)));
        }
        
        public virtual void UploadFileAttachmentSucceedsAndDisplaysLinkToFileAfterUpload(string browserName, string agreementLink, string filePath, string fileName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "InstAgrFormsR0205",
                    "InstAgrFormsFreshTestAgreementUc01"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Upload file attachment succeeds and displays link to file after upload", @__tags);
#line 96
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 98
    testRunner.Given(string.Format("I am using the {0} browser", browserName));
#line 100
    testRunner.When(string.Format("I click the \"{0}\" link", agreementLink));
#line 101
    testRunner.Then("I should see the Institutional Agreement Edit page");
#line 102
    testRunner.And("I should see a File Attachments upload field");
#line 104
    testRunner.When(string.Format("I choose the file \"{0}\" for the File Attachments upload field", filePath));
#line 105
    testRunner.Then(string.Format("I should see an item for \"{0}\" in the File Attachments list", fileName));
#line 106
    testRunner.And("I should not see the Invalid error message for the File Attachments field");
#line 108
    testRunner.When("I click the \"Save Changes\" submit button");
#line 109
    testRunner.Then("I should see the Public Institutional Agreement Detail page within 30 seconds");
#line 110
    testRunner.And(string.Format("I should see a \"{0}\" link", fileName));
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Upload file attachment succeeds and displays link to file after upload")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0205")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsFreshTestAgreementUc01")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BrowserName", "Firefox")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AgreementLink", "Agreement, UC 01 test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\SpecFlow Guide.pdf")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "SpecFlow Guide.pdf")]
        public virtual void UploadFileAttachmentSucceedsAndDisplaysLinkToFileAfterUpload_Variant0()
        {
            this.UploadFileAttachmentSucceedsAndDisplaysLinkToFileAfterUpload("Firefox", "Agreement, UC 01 test", "C:\\WebDriverFileUploads\\SpecFlow Guide.pdf", "SpecFlow Guide.pdf", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Upload file attachment succeeds and displays link to file after upload")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0205")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsFreshTestAgreementUc01")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BrowserName", "Firefox")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AgreementLink", "Agreement, UC 01 test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\WordDocument1.doc")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "WordDocument1.doc")]
        public virtual void UploadFileAttachmentSucceedsAndDisplaysLinkToFileAfterUpload_Variant1()
        {
            this.UploadFileAttachmentSucceedsAndDisplaysLinkToFileAfterUpload("Firefox", "Agreement, UC 01 test", "C:\\WebDriverFileUploads\\WordDocument1.doc", "WordDocument1.doc", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Upload file attachment succeeds and displays link to file after upload")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0205")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsFreshTestAgreementUc01")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BrowserName", "Firefox")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AgreementLink", "Agreement, UC 01 test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\WordDocument1.docx")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "WordDocument1.docx")]
        public virtual void UploadFileAttachmentSucceedsAndDisplaysLinkToFileAfterUpload_Variant2()
        {
            this.UploadFileAttachmentSucceedsAndDisplaysLinkToFileAfterUpload("Firefox", "Agreement, UC 01 test", "C:\\WebDriverFileUploads\\WordDocument1.docx", "WordDocument1.docx", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Upload file attachment succeeds and displays link to file after upload")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0205")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsFreshTestAgreementUc01")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BrowserName", "Internet Explorer")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AgreementLink", "Agreement, UC 02 test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\SpecFlow Guide.pdf")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "SpecFlow Guide.pdf")]
        public virtual void UploadFileAttachmentSucceedsAndDisplaysLinkToFileAfterUpload_Variant3()
        {
            this.UploadFileAttachmentSucceedsAndDisplaysLinkToFileAfterUpload("Internet Explorer", "Agreement, UC 02 test", "C:\\WebDriverFileUploads\\SpecFlow Guide.pdf", "SpecFlow Guide.pdf", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Upload file attachment succeeds and displays link to file after upload")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0205")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsFreshTestAgreementUc01")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BrowserName", "Internet Explorer")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AgreementLink", "Agreement, UC 02 test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\WordDocument1.doc")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "WordDocument1.doc")]
        public virtual void UploadFileAttachmentSucceedsAndDisplaysLinkToFileAfterUpload_Variant4()
        {
            this.UploadFileAttachmentSucceedsAndDisplaysLinkToFileAfterUpload("Internet Explorer", "Agreement, UC 02 test", "C:\\WebDriverFileUploads\\WordDocument1.doc", "WordDocument1.doc", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Upload file attachment succeeds and displays link to file after upload")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0205")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsFreshTestAgreementUc01")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:BrowserName", "Internet Explorer")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AgreementLink", "Agreement, UC 02 test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\WordDocument1.docx")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "WordDocument1.docx")]
        public virtual void UploadFileAttachmentSucceedsAndDisplaysLinkToFileAfterUpload_Variant5()
        {
            this.UploadFileAttachmentSucceedsAndDisplaysLinkToFileAfterUpload("Internet Explorer", "Agreement, UC 02 test", "C:\\WebDriverFileUploads\\WordDocument1.docx", "WordDocument1.docx", ((string[])(null)));
        }
        
        public virtual void UploadFileAttachmentFaileForFileOver25MegabytesInSize(string filePath, string fileName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "InstAgrFormsR0206",
                    "NotInChrome"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Upload file attachment faile for file over 25 megabytes in size", @__tags);
#line 122
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 124
    testRunner.When("I click the \"Agreement, UC 01 test\" link");
#line 125
    testRunner.Then("I should see the Institutional Agreement Edit page");
#line 126
    testRunner.And("I should see a File Attachments upload field");
#line 128
    testRunner.When(string.Format("I choose the file \"{0}\" for the File Attachments upload field", filePath));
#line 129
    testRunner.Then(string.Format("I should see an item for \"{0}\" in the File Attachments list", fileName));
#line 131
    testRunner.When("I click the \"Save Changes\" submit button");
#line 132
    testRunner.Then("I should see the File Upload Too Large page within 60 seconds");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Upload file attachment faile for file over 25 megabytes in size")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR02")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0206")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NotInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "C:\\WebDriverFileUploads\\LargePdf33.8.pdf")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FilePath", "C:\\WebDriverFileUploads\\LargePdf33.8.pdf")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:FileName", "LargePdf33.8.pdf")]
        public virtual void UploadFileAttachmentFaileForFileOver25MegabytesInSize_CWebDriverFileUploadsLargePdf33_8_Pdf()
        {
            this.UploadFileAttachmentFaileForFileOver25MegabytesInSize("C:\\WebDriverFileUploads\\LargePdf33.8.pdf", "LargePdf33.8.pdf", ((string[])(null)));
        }
    }
}
#pragma warning restore
#endregion
