// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.239
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UCosmic.Www.Mvc.Areas.InstitutionalAgreements
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class InstitutionalAgreementManagementPreviewRevision4Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ManagementFormsR04.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Institutional Agreement Management Preview Revision 4", @"  In order to inform the people about the use of an expiration date field for my Institutional Agreements
  As an Institutional Agreement Manager
  I want to help the people enter expiration date information attached to my Institutional Agreements in UCosmic", ProgrammingLanguage.CSharp, new string[] {
                        "InstAgrForms",
                        "InstAgrFormsR04"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Institutional Agreement Management Preview Revision 4")))
            {
                UCosmic.Www.Mvc.Areas.InstitutionalAgreements.InstitutionalAgreementManagementPreviewRevision4Feature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 9
#line 10
 testRunner.Given("I have signed in as \"manager1@uc.edu\" with password \"asdfasdf\"");
#line 11
 testRunner.And("I have browsed to the \"my/institutional-agreements/v1\" url");
#line hidden
        }
        
        public virtual void InstitutionalAgreementFormsDisplayTheHelpLink(string addOrEdit, string linkText, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "InstAgrFormsR0401"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Institutional Agreement forms display the Help link", @__tags);
#line 14
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 15
    testRunner.When(string.Format("I click the \"{0}\" link", linkText));
#line 16
    testRunner.And(string.Format("I see a page at the \"my/institutional-agreements/v1/[PathVar]/{0}\" url", addOrEdit));
#line 17
    testRunner.Then("I should see a \"Help\" link");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Institutional Agreement forms display the Help link")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR04")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0401")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "new")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "new")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Add a new agreement")]
        public virtual void InstitutionalAgreementFormsDisplayTheHelpLink_New()
        {
            this.InstitutionalAgreementFormsDisplayTheHelpLink("new", "Add a new agreement", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Institutional Agreement forms display the Help link")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR04")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0401")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Agreement, UC 01 test")]
        public virtual void InstitutionalAgreementFormsDisplayTheHelpLink_Edit()
        {
            this.InstitutionalAgreementFormsDisplayTheHelpLink("edit", "Agreement, UC 01 test", ((string[])(null)));
        }
        
        public virtual void InstitutionalAgreementFormsSuccessfullyDisplaysBubblePopUpForTheHelpLink(string addOrEdit, string linkText, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "InstAgrFormsR0402"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Institutional Agreement forms successfully displays bubble pop up for the Help li" +
                    "nk", @__tags);
#line 24
 this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 25
    testRunner.Given(string.Format("I have clicked the \"{0}\" link", linkText));
#line 26
    testRunner.And(string.Format("I have seen a page at the \"my/institutional-agreements/v1/[PathVar]/{0}\" url", addOrEdit));
#line 27
    testRunner.And("I have seen a \"Help\" link");
#line 28
    testRunner.When("I click the \"Help\" link");
#line 29
    testRunner.Then(string.Format("I should see a bubble pop up in the Institutional Agreements {0} form", addOrEdit));
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Institutional Agreement forms successfully displays bubble pop up for the Help li" +
            "nk")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR04")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0402")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "new")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "new")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Add a new agreement")]
        public virtual void InstitutionalAgreementFormsSuccessfullyDisplaysBubblePopUpForTheHelpLink_New()
        {
            this.InstitutionalAgreementFormsSuccessfullyDisplaysBubblePopUpForTheHelpLink("new", "Add a new agreement", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Institutional Agreement forms successfully displays bubble pop up for the Help li" +
            "nk")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR04")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0402")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Agreement, UC 01 test")]
        public virtual void InstitutionalAgreementFormsSuccessfullyDisplaysBubblePopUpForTheHelpLink_Edit()
        {
            this.InstitutionalAgreementFormsSuccessfullyDisplaysBubblePopUpForTheHelpLink("edit", "Agreement, UC 01 test", ((string[])(null)));
        }
        
        public virtual void InstitutionalAgreementFormsSuccessfullyClosesTheBubblePopUpForTheHelpLink(string addOrEdit, string linkText, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "InstAgrFormsR0403"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Institutional Agreement forms successfully closes the bubble pop up for the Help " +
                    "link", @__tags);
#line 36
 this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 37
    testRunner.Given(string.Format("I have clicked the \"{0}\" link", linkText));
#line 38
    testRunner.And(string.Format("I have seen a page at the \"my/institutional-agreements/v1/[PathVar]/{0}\" url", addOrEdit));
#line 39
    testRunner.And("I have seen a \"Help\" link");
#line 40
    testRunner.And("I have clicked the \"Help\" link");
#line 41
    testRunner.And(string.Format("I have seen a bubble pop up in the Institutional Agreements {0} form", addOrEdit));
#line 42
    testRunner.When("I click the \"Close this popup\" link");
#line 43
    testRunner.Then(string.Format("I should not see a bubble pop up in the Institutional Agreements {0} form", addOrEdit));
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Institutional Agreement forms successfully closes the bubble pop up for the Help " +
            "link")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR04")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0403")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "new")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "new")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Add a new agreement")]
        public virtual void InstitutionalAgreementFormsSuccessfullyClosesTheBubblePopUpForTheHelpLink_New()
        {
            this.InstitutionalAgreementFormsSuccessfullyClosesTheBubblePopUpForTheHelpLink("new", "Add a new agreement", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Institutional Agreement forms successfully closes the bubble pop up for the Help " +
            "link")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR04")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0403")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Agreement, UC 01 test")]
        public virtual void InstitutionalAgreementFormsSuccessfullyClosesTheBubblePopUpForTheHelpLink_Edit()
        {
            this.InstitutionalAgreementFormsSuccessfullyClosesTheBubblePopUpForTheHelpLink("edit", "Agreement, UC 01 test", ((string[])(null)));
        }
        
        public virtual void InstitutionalAgreementFormsSuccessfullyClosesTheBubblePopUpForTheHelpLinkByClickingTheHelpLink(string addOrEdit, string linkText, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "InstAgrFormsR0404"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Institutional Agreement forms successfully closes the bubble pop up for the Help " +
                    "link by clicking the help link", @__tags);
#line 50
 this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 51
    testRunner.Given(string.Format("I have clicked the \"{0}\" link", linkText));
#line 52
    testRunner.And(string.Format("I have seen a page at the \"my/institutional-agreements/v1/[PathVar]/{0}\" url", addOrEdit));
#line 53
    testRunner.And("I have seen a \"Help\" link");
#line 54
    testRunner.And("I have clicked the \"Help\" link");
#line 55
    testRunner.And(string.Format("I have seen a bubble pop up in the Institutional Agreements {0} form", addOrEdit));
#line 56
    testRunner.When("I click the \"Help\" link");
#line 57
    testRunner.Then(string.Format("I should not see a bubble pop up in the Institutional Agreements {0} form", addOrEdit));
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Institutional Agreement forms successfully closes the bubble pop up for the Help " +
            "link by clicking the help link")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR04")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0404")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "new")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "new")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Add a new agreement")]
        public virtual void InstitutionalAgreementFormsSuccessfullyClosesTheBubblePopUpForTheHelpLinkByClickingTheHelpLink_New()
        {
            this.InstitutionalAgreementFormsSuccessfullyClosesTheBubblePopUpForTheHelpLinkByClickingTheHelpLink("new", "Add a new agreement", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Institutional Agreement forms successfully closes the bubble pop up for the Help " +
            "link by clicking the help link")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Institutional Agreement Management Preview Revision 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrForms")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR04")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InstAgrFormsR0404")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AddOrEdit", "edit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:LinkText", "Agreement, UC 01 test")]
        public virtual void InstitutionalAgreementFormsSuccessfullyClosesTheBubblePopUpForTheHelpLinkByClickingTheHelpLink_Edit()
        {
            this.InstitutionalAgreementFormsSuccessfullyClosesTheBubblePopUpForTheHelpLinkByClickingTheHelpLink("edit", "Agreement, UC 01 test", ((string[])(null)));
        }
    }
}
#pragma warning restore
#endregion
