// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.239
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UCosmic.Www.Mvc.Areas.Identity
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class UserChangeEmailSpellingFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SelfR03.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "User Change Email Spelling", "     In order to correct mistakes in capitalization\r\n     As a UCosmic.com user\r\n" +
                    "     I want to change the spelling of my email addresses", ProgrammingLanguage.CSharp, new string[] {
                        "Self",
                        "SelfR03"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "User Change Email Spelling")))
            {
                UCosmic.Www.Mvc.Areas.Identity.UserChangeEmailSpellingFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 9
#line 10
    testRunner.Given("I have signed in as \"any1@uc.edu\" with password \"asdfasdf\"");
#line 11
    testRunner.And("I have browsed to the \"my/profile\" url");
#line hidden
        }
        
        public virtual void MyChangeEmailSpellingFormChangesSpellingUnsuccessfullyWithInvalidInputs(string newSpelling, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "SelfRespellEmail",
                    "SelfR0301"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("My Change Email Spelling form changes spelling unsuccessfully with invalid inputs" +
                    "", @__tags);
#line 15
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 16
 testRunner.Given("I have clicked the \"Change spelling\" link");
#line 17
 testRunner.And("I have seen a page at the \"me/emails/[PathVar]/change-spelling.html\" url");
#line 18
 testRunner.When(string.Format("I type \"{0}\" into the \"Value\" text box on the Change Email Spelling form", newSpelling));
#line 19
 testRunner.And("I click the \"Save Changes\" button on the Change Email Spelling form");
#line 20
 testRunner.Then("I should see the error message \"You can only change lowercase letters to uppercas" +
                    "e (or vice versa) when changing the spelling of your email address.\" for the \"Va" +
                    "lue\" text box on the Change Email Spelling form");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("My Change Email Spelling form changes spelling unsuccessfully with invalid inputs" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User Change Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Self")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR03")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfRespellEmail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR0301")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NewSpelling", "")]
        public virtual void MyChangeEmailSpellingFormChangesSpellingUnsuccessfullyWithInvalidInputs_()
        {
            this.MyChangeEmailSpellingFormChangesSpellingUnsuccessfullyWithInvalidInputs("", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("My Change Email Spelling form changes spelling unsuccessfully with invalid inputs" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User Change Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Self")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR03")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfRespellEmail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR0301")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "junkvalues")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NewSpelling", "junkvalues")]
        public virtual void MyChangeEmailSpellingFormChangesSpellingUnsuccessfullyWithInvalidInputs_Junkvalues()
        {
            this.MyChangeEmailSpellingFormChangesSpellingUnsuccessfullyWithInvalidInputs("junkvalues", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("My Change Email Spelling form changes spelling unsuccessfully with invalid inputs" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User Change Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Self")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR03")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfRespellEmail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR0301")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "fkdkd@skd.csks")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NewSpelling", "fkdkd@skd.csks")]
        public virtual void MyChangeEmailSpellingFormChangesSpellingUnsuccessfullyWithInvalidInputs_FkdkdSkd_Csks()
        {
            this.MyChangeEmailSpellingFormChangesSpellingUnsuccessfullyWithInvalidInputs("fkdkd@skd.csks", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("My Change Email Spelling form changes spelling unsuccessfully with invalid inputs" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User Change Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Self")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR03")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfRespellEmail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR0301")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "any2@uc.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NewSpelling", "any2@uc.edu")]
        public virtual void MyChangeEmailSpellingFormChangesSpellingUnsuccessfullyWithInvalidInputs_Any2Uc_Edu()
        {
            this.MyChangeEmailSpellingFormChangesSpellingUnsuccessfullyWithInvalidInputs("any2@uc.edu", ((string[])(null)));
        }
        
        public virtual void MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingChrome(string newEmailAddress, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "SelfRespellEmail",
                    "SelfR0302A",
                    "OnlyInChrome"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("My Change Email Spelling form changes spelling successfully with valid inputs usi" +
                    "ng Chrome", @__tags);
#line 31
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 32
 testRunner.Given("I have seen a \"Change spelling\" link");
#line 33
 testRunner.And("I have clicked the \"Change spelling\" link");
#line 34
 testRunner.And("I have seen a page at the \"me/emails/[PathVar]/change-spelling.html\" url");
#line 35
 testRunner.When(string.Format("I type \"{0}\" into the \"Value\" text box on the Change Email Spelling form", newEmailAddress));
#line 36
 testRunner.And("I click the \"Save Changes\" button on the Change Email Spelling form");
#line 37
 testRunner.Then("I should see a page at the \"my/profile\" url");
#line 38
 testRunner.And(string.Format("I should see top feedback message \"Your email address was successfully changed to" +
                        " {0}.\"", newEmailAddress));
#line 39
    testRunner.And(string.Format("I should see the email address \"{0}\" in the My Email Addresses form", newEmailAddress));
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("My Change Email Spelling form changes spelling successfully with valid inputs usi" +
            "ng Chrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User Change Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Self")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR03")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfRespellEmail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR0302A")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OnlyInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "any1@uc.EDU")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NewEmailAddress", "any1@uc.EDU")]
        public virtual void MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingChrome_Any1Uc_EDU()
        {
            this.MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingChrome("any1@uc.EDU", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("My Change Email Spelling form changes spelling successfully with valid inputs usi" +
            "ng Chrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User Change Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Self")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR03")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfRespellEmail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR0302A")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OnlyInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "ANY1@UC.EDU")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NewEmailAddress", "ANY1@UC.EDU")]
        public virtual void MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingChrome_ANY1UC_EDU()
        {
            this.MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingChrome("ANY1@UC.EDU", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("My Change Email Spelling form changes spelling successfully with valid inputs usi" +
            "ng Chrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User Change Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Self")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR03")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfRespellEmail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR0302A")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OnlyInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "ANY1@uc.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NewEmailAddress", "ANY1@uc.edu")]
        public virtual void MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingChrome_ANY1Uc_Edu()
        {
            this.MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingChrome("ANY1@uc.edu", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("My Change Email Spelling form changes spelling successfully with valid inputs usi" +
            "ng Chrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User Change Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Self")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR03")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfRespellEmail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR0302A")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OnlyInChrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "any1@uc.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NewEmailAddress", "any1@uc.edu")]
        public virtual void MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingChrome_Any1Uc_Edu()
        {
            this.MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingChrome("any1@uc.edu", ((string[])(null)));
        }
        
        public virtual void MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingFirefox(string newEmailAddress, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "SelfRespellEmail",
                    "SelfR0302B",
                    "OnlyInFirefox"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("My Change Email Spelling form changes spelling successfully with valid inputs usi" +
                    "ng Firefox", @__tags);
#line 50
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 51
 testRunner.Given("I have seen a \"Change spelling\" link");
#line 52
 testRunner.And("I have clicked the \"Change spelling\" link");
#line 53
 testRunner.And("I have seen a page at the \"me/emails/[PathVar]/change-spelling.html\" url");
#line 54
 testRunner.When(string.Format("I type \"{0}\" into the \"Value\" text box on the Change Email Spelling form", newEmailAddress));
#line 55
 testRunner.And("I click the \"Save Changes\" button on the Change Email Spelling form");
#line 56
 testRunner.Then("I should see a page at the \"my/profile\" url");
#line 57
 testRunner.And(string.Format("I should see top feedback message \"Your email address was successfully changed to" +
                        " {0}.\"", newEmailAddress));
#line 58
    testRunner.And(string.Format("I should see the email address \"{0}\" in the My Email Addresses form", newEmailAddress));
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("My Change Email Spelling form changes spelling successfully with valid inputs usi" +
            "ng Firefox")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User Change Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Self")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR03")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfRespellEmail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR0302B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OnlyInFirefox")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "any1@uc.EDU")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NewEmailAddress", "any1@uc.EDU")]
        public virtual void MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingFirefox_Any1Uc_EDU()
        {
            this.MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingFirefox("any1@uc.EDU", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("My Change Email Spelling form changes spelling successfully with valid inputs usi" +
            "ng Firefox")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User Change Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Self")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR03")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfRespellEmail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR0302B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OnlyInFirefox")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "ANY1@UC.EDU")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NewEmailAddress", "ANY1@UC.EDU")]
        public virtual void MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingFirefox_ANY1UC_EDU()
        {
            this.MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingFirefox("ANY1@UC.EDU", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("My Change Email Spelling form changes spelling successfully with valid inputs usi" +
            "ng Firefox")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User Change Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Self")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR03")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfRespellEmail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR0302B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OnlyInFirefox")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "ANY1@uc.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NewEmailAddress", "ANY1@uc.edu")]
        public virtual void MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingFirefox_ANY1Uc_Edu()
        {
            this.MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingFirefox("ANY1@uc.edu", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("My Change Email Spelling form changes spelling successfully with valid inputs usi" +
            "ng Firefox")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User Change Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Self")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR03")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfRespellEmail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR0302B")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OnlyInFirefox")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "any1@uc.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NewEmailAddress", "any1@uc.edu")]
        public virtual void MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingFirefox_Any1Uc_Edu()
        {
            this.MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingFirefox("any1@uc.edu", ((string[])(null)));
        }
        
        public virtual void MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingInternetExplorer(string newEmailAddress, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "SelfRespellEmail",
                    "SelfR0302C",
                    "OnlyInInternetExplorer"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("My Change Email Spelling form changes spelling successfully with valid inputs usi" +
                    "ng Internet Explorer", @__tags);
#line 69
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 70
 testRunner.Given("I have seen a \"Change spelling\" link");
#line 71
 testRunner.And("I have clicked the \"Change spelling\" link");
#line 72
 testRunner.And("I have seen a page at the \"me/emails/[PathVar]/change-spelling.html\" url");
#line 73
 testRunner.When(string.Format("I type \"{0}\" into the \"Value\" text box on the Change Email Spelling form", newEmailAddress));
#line 74
 testRunner.And("I click the \"Save Changes\" button on the Change Email Spelling form");
#line 75
 testRunner.Then("I should see a page at the \"my/profile\" url");
#line 76
 testRunner.And(string.Format("I should see top feedback message \"Your email address was successfully changed to" +
                        " {0}.\"", newEmailAddress));
#line 77
    testRunner.And(string.Format("I should see the email address \"{0}\" in the My Email Addresses form", newEmailAddress));
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("My Change Email Spelling form changes spelling successfully with valid inputs usi" +
            "ng Internet Explorer")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User Change Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Self")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR03")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfRespellEmail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR0302C")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OnlyInInternetExplorer")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "any1@uc.EDU")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NewEmailAddress", "any1@uc.EDU")]
        public virtual void MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingInternetExplorer_Any1Uc_EDU()
        {
            this.MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingInternetExplorer("any1@uc.EDU", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("My Change Email Spelling form changes spelling successfully with valid inputs usi" +
            "ng Internet Explorer")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User Change Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Self")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR03")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfRespellEmail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR0302C")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OnlyInInternetExplorer")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "ANY1@UC.EDU")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NewEmailAddress", "ANY1@UC.EDU")]
        public virtual void MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingInternetExplorer_ANY1UC_EDU()
        {
            this.MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingInternetExplorer("ANY1@UC.EDU", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("My Change Email Spelling form changes spelling successfully with valid inputs usi" +
            "ng Internet Explorer")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User Change Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Self")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR03")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfRespellEmail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR0302C")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OnlyInInternetExplorer")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "ANY1@uc.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NewEmailAddress", "ANY1@uc.edu")]
        public virtual void MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingInternetExplorer_ANY1Uc_Edu()
        {
            this.MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingInternetExplorer("ANY1@uc.edu", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("My Change Email Spelling form changes spelling successfully with valid inputs usi" +
            "ng Internet Explorer")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User Change Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Self")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR03")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfRespellEmail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR0302C")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OnlyInInternetExplorer")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "any1@uc.edu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NewEmailAddress", "any1@uc.edu")]
        public virtual void MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingInternetExplorer_Any1Uc_Edu()
        {
            this.MyChangeEmailSpellingFormChangesSpellingSuccessfullyWithValidInputsUsingInternetExplorer("any1@uc.edu", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("My Change Email Spelling form successfully dismiss by clicking Cancel button")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "User Change Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Self")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR03")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfRespellEmail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SelfR0303")]
        public virtual void MyChangeEmailSpellingFormSuccessfullyDismissByClickingCancelButton()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("My Change Email Spelling form successfully dismiss by clicking Cancel button", new string[] {
                        "SelfRespellEmail",
                        "SelfR0303"});
#line 87
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 88
    testRunner.Given("I have clicked the \"Change spelling\" link");
#line 89
    testRunner.And("I have seen a page at the \"me/emails/[PathVar]/change-spelling.html\" url");
#line 90
    testRunner.When("I click the \"Cancel\" button on the Change Email Spelling form");
#line 91
    testRunner.Then("I should see a page at the \"my/profile\" url");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
