// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.17626
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UCosmic.Www.Mvc.Areas.Identity
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ChangeMyEmailSpellingFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "UpdateEmailSpelling.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Change My Email Spelling", "  In order to correct mistakes in capitalization\r\n  As a UCosmic.com user\r\n  I wa" +
                    "nt to change the spelling of my email addresses", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Change My Email Spelling")))
            {
                UCosmic.Www.Mvc.Areas.Identity.ChangeMyEmailSpellingFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void ChangesEmailSpelling(string browser, string emailAddress, string newSpelling, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "UsingFreshExampleEmailSpellingForAny1AtUsil"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Changes Email Spelling", @__tags);
#line 7
this.ScenarioSetup(scenarioInfo);
#line 9
    testRunner.Given(string.Format("I am using the {0} browser", browser));
#line 10
    testRunner.And(string.Format("I am signed in as {0}", emailAddress));
#line 11
    testRunner.And("I am starting from the Personal Home page");
#line 12
    testRunner.And("I see a link titled \"Change spelling\"");
#line 14
    testRunner.When("I click the link titled \"Change spelling\"");
#line 15
    testRunner.Then("I should see the Update Email Spelling page");
#line 16
    testRunner.And("I should see a \"Cancel\" link");
#line 19
    testRunner.When("I click the \"Cancel\" link");
#line 20
    testRunner.Then("I should see the Personal Home page");
#line 21
    testRunner.When("I click the link titled \"Change spelling\"");
#line 22
    testRunner.Then("I should see the Update Email Spelling page");
#line 25
    testRunner.When("I type \"\" into the New Spelling text field");
#line 26
    testRunner.And("I click the \"Save Changes\" submit button");
#line 27
    testRunner.Then("I should still see the Update Email Spelling page");
#line 28
    testRunner.And("I should see the Invalid error message for the New Spelling text field");
#line 31
    testRunner.When("I type \"incorrect\" into the New Spelling text field");
#line 32
    testRunner.And("I click the \"Save Changes\" submit button");
#line 33
    testRunner.Then("I should still see the Update Email Spelling page");
#line 34
    testRunner.And("I should see the Invalid error message for the New Spelling text field");
#line 37
    testRunner.When(string.Format("I type \"{0}\" into the New Spelling text field", newSpelling));
#line 38
    testRunner.And("I click the \"Save Changes\" submit button");
#line 39
    testRunner.Then("I should see the Personal Home page");
#line 40
    testRunner.And(string.Format("I should see the flash feedback message \"Your email address was successfully chan" +
                        "ged to {0}.\"", newSpelling));
#line 41
    testRunner.And(string.Format("I should see a \"{0}\" link", newSpelling));
#line 44
    testRunner.When(string.Format("I click the \"{0}\" link", newSpelling));
#line 45
    testRunner.Then("I should see the Update Email Spelling page");
#line 46
    testRunner.And(string.Format("I should see \"{0}\" in the New Spelling text field", newSpelling));
#line 48
    testRunner.When(string.Format("I type \"{0}\" into the New Spelling text field", emailAddress));
#line 49
    testRunner.And("I click the \"Save Changes\" submit button");
#line 50
    testRunner.Then("I should see the Personal Home page");
#line 51
    testRunner.And(string.Format("I should see the flash feedback message \"Your email address was successfully chan" +
                        "ged to {0}.\"", emailAddress));
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Changes Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Change My Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UsingFreshExampleEmailSpellingForAny1AtUsil")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Chrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "Chrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:EmailAddress", "any1@usil.edu.pe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NewSpelling", "ANY1@USIL.EDU.PE")]
        public virtual void ChangesEmailSpelling_Chrome()
        {
            this.ChangesEmailSpelling("Chrome", "any1@usil.edu.pe", "ANY1@USIL.EDU.PE", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Changes Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Change My Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UsingFreshExampleEmailSpellingForAny1AtUsil")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Firefox")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "Firefox")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:EmailAddress", "any1@bjtu.edu.cn")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NewSpelling", "ANY1@BJTU.EDU.CN")]
        public virtual void ChangesEmailSpelling_Firefox()
        {
            this.ChangesEmailSpelling("Firefox", "any1@bjtu.edu.cn", "ANY1@BJTU.EDU.CN", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Changes Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Change My Email Spelling")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UsingFreshExampleEmailSpellingForAny1AtUsil")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "MSIE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "MSIE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:EmailAddress", "any1@napier.ac.uk")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NewSpelling", "ANY1@NAPIER.AC.UK")]
        public virtual void ChangesEmailSpelling_MSIE()
        {
            this.ChangesEmailSpelling("MSIE", "any1@napier.ac.uk", "ANY1@NAPIER.AC.UK", ((string[])(null)));
        }
    }
}
#pragma warning restore
#endregion
