// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.17626
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UCosmic.Www.Mvc.Areas.Identity
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class UpdateMyAffiliationFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "UpdateAffiliation.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Update My Affiliation", "  In order to control what UCosmic says about me\r\n  As a UCosmic user\r\n  I want t" +
                    "o update my affiliation and employment information", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Update My Affiliation")))
            {
                UCosmic.Www.Mvc.Areas.Identity.UpdateMyAffiliationFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void UpdateAffiliatonTypeEmploymentCategoriesAndJobTitles(string browser, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "UsingFreshExampleDefaultAffiliationForAny1AtUsil"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update Affiliaton Type, Employment Categories, and Job Titles", @__tags);
#line 7
this.ScenarioSetup(scenarioInfo);
#line 9
    testRunner.Given(string.Format("I am using the {0} browser", browser));
#line 10
    testRunner.And("I am signed in as any1@usil.edu.pe");
#line 11
    testRunner.And("I am starting from the Personal Home page");
#line 12
    testRunner.When("I click the \"Set up affiliation\" link");
#line 13
    testRunner.Then("I should see the Personal Affiliation page");
#line 14
    testRunner.And("I should see a \"Cancel\" link");
#line 16
    testRunner.When("I check the Affiliation Type radio button labeled \'I am an employee.\'");
#line 17
    testRunner.Then("I should see an \'Additional Employee Details\' section");
#line 18
    testRunner.And("I should see an \'International Office Employee\' check box");
#line 19
    testRunner.And("I should see an \'Administrator Employee\' check box");
#line 20
    testRunner.And("I should see an \'Faculty Employee\' check box");
#line 21
    testRunner.And("I should see an \'Staff Employee\' check box");
#line 24
    testRunner.When("I check the \'Administrator Employee\' check box");
#line 25
    testRunner.And("I check the \'Staff Employee\' check box");
#line 26
    testRunner.And("I click the \"Save Changes\" submit button");
#line 27
    testRunner.Then("I should see the Personal Home page");
#line 28
    testRunner.And("I should see the flash feedback message \"Your affiliation info was successfully u" +
                    "pdated.\"");
#line 29
    testRunner.And("I should see an \"Edit affiliation info\" link");
#line 31
    testRunner.When("I click the \"Edit affiliation info\" link");
#line 32
    testRunner.Then("I should see the Personal Affiliation page");
#line 33
    testRunner.And("the \'Administrator Employee\' check box should be checked");
#line 34
    testRunner.And("the \'Staff Employee\' check box should be checked");
#line 37
    testRunner.When("I uncheck the \'Administrator Employee\' check box");
#line 38
    testRunner.And("I uncheck the \'Staff Employee\' check box");
#line 39
    testRunner.And("I click the \"Save Changes\" submit button");
#line 40
    testRunner.Then("I should see the Personal Home page");
#line 41
    testRunner.And("I should see the flash feedback message \"Your affiliation info was successfully u" +
                    "pdated.\"");
#line 42
    testRunner.And("I should see an \"Edit affiliation info\" link");
#line 44
    testRunner.When("I click the \"Edit affiliation info\" link");
#line 45
    testRunner.Then("I should see the Personal Affiliation page");
#line 46
    testRunner.And("the \'Administrator Employee\' check box should be unchecked");
#line 47
    testRunner.And("the \'Staff Employee\' check box should be unchecked");
#line 50
    testRunner.When("I check the \'International Office Employee\' check box");
#line 51
    testRunner.And("I check the \'Faculty Employee\' check box");
#line 52
    testRunner.And("I click the \"Save Changes\" submit button");
#line 53
    testRunner.Then("I should see the Personal Home page");
#line 54
    testRunner.And("I should see the flash feedback message \"Your affiliation info was successfully u" +
                    "pdated.\"");
#line 55
    testRunner.And("I should see an \"Edit affiliation info\" link");
#line 57
    testRunner.When("I click the \"Edit affiliation info\" link");
#line 58
    testRunner.Then("I should see the Personal Affiliation page");
#line 59
    testRunner.And("the \'International Office Employee\' check box should be checked");
#line 60
    testRunner.And("the \'Faculty Employee\' check box should be checked");
#line 63
    testRunner.When("I uncheck the \'International Office Employee\' check box");
#line 64
    testRunner.And("I uncheck the \'Faculty Employee\' check box");
#line 65
    testRunner.And("I click the \"Save Changes\" submit button");
#line 66
    testRunner.Then("I should see the Personal Home page");
#line 67
    testRunner.And("I should see the flash feedback message \"Your affiliation info was successfully u" +
                    "pdated.\"");
#line 68
    testRunner.And("I should see an \"Edit affiliation info\" link");
#line 70
    testRunner.When("I click the \"Edit affiliation info\" link");
#line 71
    testRunner.Then("I should see the Personal Affiliation page");
#line 72
    testRunner.And("the \'International Office Employee\' check box should be unchecked");
#line 73
    testRunner.And("the \'Faculty Employee\' check box should be unchecked");
#line 76
    testRunner.When("I click the \"Cancel\" link");
#line 77
    testRunner.Then("I should see the Personal Home page");
#line 78
    testRunner.When("I click the \"Edit affiliation info\" link");
#line 79
    testRunner.Then("I should see the Personal Affiliation page");
#line 82
    testRunner.When("I check the Affiliation Type radio button labeled \'I am an employee.\'");
#line 83
    testRunner.Then("I should see an \'Additional Employee Details\' section");
#line 85
    testRunner.When("I type \"\" into the Job Titles & Departments text field");
#line 86
    testRunner.And("I click the \"Save Changes\" submit button");
#line 87
    testRunner.Then("I should see the Personal Home page");
#line 88
    testRunner.And("I should see the flash feedback message \"Your affiliation info was successfully u" +
                    "pdated.\"");
#line 89
    testRunner.And("I should see an \"Edit affiliation info\" link");
#line 90
    testRunner.And("I should see \"[Job Title(s) Unknown]\" in the Affiliation Details section");
#line 93
    testRunner.When("I click the \"Edit affiliation info\" link");
#line 94
    testRunner.Then("I should see the Personal Affiliation page");
#line 96
    testRunner.When("I check the Affiliation Type radio button labeled \'I am a student.\'");
#line 97
    testRunner.Then("I should not see an \'Additional Employee Details\' section");
#line 99
    testRunner.When("I click the \"Save Changes\" submit button");
#line 100
    testRunner.Then("I should see the Personal Home page");
#line 101
    testRunner.And("I should see the flash feedback message \"Your affiliation info was successfully u" +
                    "pdated.\"");
#line 102
    testRunner.And("I should see \"Student\" in the Affiliation Details section");
#line 105
    testRunner.When("I click the \"Edit affiliation info\" link");
#line 106
    testRunner.Then("I should see the Personal Affiliation page");
#line 108
    testRunner.When("I check the Affiliation Type radio button labeled \'I am both an employee and a st" +
                    "udent.\'");
#line 109
    testRunner.Then("I should see an \'Additional Employee Details\' section");
#line 111
    testRunner.When("I type \"\" into the Job Titles & Departments text field");
#line 112
    testRunner.And("I click the \"Save Changes\" submit button");
#line 113
    testRunner.Then("I should see the Personal Home page");
#line 114
    testRunner.And("I should see the flash feedback message \"Your affiliation info was successfully u" +
                    "pdated.\"");
#line 115
    testRunner.And("I should see \"[Job Title(s) Unknown]\" in the Affiliation Details section");
#line 118
    testRunner.When("I click the \"Edit affiliation info\" link");
#line 119
    testRunner.Then("I should see the Personal Affiliation page");
#line 121
    testRunner.When("I check the Affiliation Type radio button labeled \'I am neither an employee nor a" +
                    " student.\'");
#line 122
    testRunner.Then("I should not see an \'Additional Employee Details\' section");
#line 124
    testRunner.When("I click the \"Save Changes\" submit button");
#line 125
    testRunner.Then("I should see the Personal Home page");
#line 126
    testRunner.And("I should see the flash feedback message \"Your affiliation info was successfully u" +
                    "pdated.\"");
#line 127
    testRunner.And("I should see an \"Edit affiliation info\" link");
#line 128
    testRunner.And("I should see \"Neither student nor employee\" in the Affiliation Details section");
#line 131
    testRunner.When("I click the \"Edit affiliation info\" link");
#line 132
    testRunner.Then("I should see the Personal Affiliation page");
#line 134
    testRunner.When("I check the Affiliation Type radio button labeled \'I am an employee.\'");
#line 135
    testRunner.Then("I should see an \'Additional Employee Details\' section");
#line 137
    testRunner.When("I type \"Applications Analyst\" into the Job Titles & Departments text field");
#line 138
    testRunner.And("I click the \"Save Changes\" submit button");
#line 139
    testRunner.Then("I should see the Personal Home page");
#line 140
    testRunner.And("I should see the flash feedback message \"Your affiliation info was successfully u" +
                    "pdated.\"");
#line 141
    testRunner.And("I should see \"Applications Analyst\" in the Affiliation Details section");
#line 144
    testRunner.When("I click the \"Edit affiliation info\" link");
#line 145
    testRunner.Then("I should see the Personal Affiliation page");
#line 147
    testRunner.When("I check the Affiliation Type radio button labeled \'I am both an employee and a st" +
                    "udent.\'");
#line 148
    testRunner.Then("I should see an \'Additional Employee Details\' section");
#line 150
    testRunner.When("I type \"Teaching Assistant\" into the Job Titles & Departments text field");
#line 151
    testRunner.And("I click the \"Save Changes\" submit button");
#line 152
    testRunner.Then("I should see the Personal Home page");
#line 153
    testRunner.And("I should see the flash feedback message \"Your affiliation info was successfully u" +
                    "pdated.\"");
#line 154
    testRunner.And("I should see \"Teaching Assistant\" in the Affiliation Details section");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Update Affiliaton Type, Employment Categories, and Job Titles")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Update My Affiliation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UsingFreshExampleDefaultAffiliationForAny1AtUsil")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Chrome")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "Chrome")]
        public virtual void UpdateAffiliatonTypeEmploymentCategoriesAndJobTitles_Chrome()
        {
            this.UpdateAffiliatonTypeEmploymentCategoriesAndJobTitles("Chrome", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Update Affiliaton Type, Employment Categories, and Job Titles")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Update My Affiliation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UsingFreshExampleDefaultAffiliationForAny1AtUsil")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Firefox")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "Firefox")]
        public virtual void UpdateAffiliatonTypeEmploymentCategoriesAndJobTitles_Firefox()
        {
            this.UpdateAffiliatonTypeEmploymentCategoriesAndJobTitles("Firefox", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Update Affiliaton Type, Employment Categories, and Job Titles")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Update My Affiliation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UsingFreshExampleDefaultAffiliationForAny1AtUsil")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "MSIE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Browser", "MSIE")]
        public virtual void UpdateAffiliatonTypeEmploymentCategoriesAndJobTitles_MSIE()
        {
            this.UpdateAffiliatonTypeEmploymentCategoriesAndJobTitles("MSIE", ((string[])(null)));
        }
    }
}
#pragma warning restore
#endregion
