// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace UCosmic.Www.Mvc.Areas.Common.Controllers {
    public partial class FeaturesController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public FeaturesController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected FeaturesController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public FeaturesController Actions { get { return MVC.Common.Features; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Common";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Features";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Features";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Releases = "releases";
            public readonly string ReleasesNav = "releases-nav";
            public readonly string Requirements = "requirements";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Releases = "releases";
            public const string ReleasesNav = "releases-nav";
            public const string Requirements = "requirements";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string alumni_module = "~/Areas/Common/Views/Features/alumni-module.cshtml";
            public readonly string corporate_engagement_module = "~/Areas/Common/Views/Features/corporate-engagement-module.cshtml";
            public readonly string december_2011_preview_1 = "~/Areas/Common/Views/Features/december-2011-preview-1.cshtml";
            public readonly string december_2011_preview_2 = "~/Areas/Common/Views/Features/december-2011-preview-2.cshtml";
            public readonly string faculty_staff_module = "~/Areas/Common/Views/Features/faculty-staff-module.cshtml";
            public readonly string february_2012_preview_1 = "~/Areas/Common/Views/Features/february-2012-preview-1.cshtml";
            public readonly string february_2012_preview_2 = "~/Areas/Common/Views/Features/february-2012-preview-2.cshtml";
            public readonly string gherkin = "~/Areas/Common/Views/Features/gherkin.cshtml";
            public readonly string global_press_module = "~/Areas/Common/Views/Features/global-press-module.cshtml";
            public readonly string july_2012_preview_1 = "~/Areas/Common/Views/Features/july-2012-preview-1.cshtml";
            public readonly string june_2012_preview_1 = "~/Areas/Common/Views/Features/june-2012-preview-1.cshtml";
            public readonly string june_2012_preview_2 = "~/Areas/Common/Views/Features/june-2012-preview-2.cshtml";
            public readonly string preview_1 = "~/Areas/Common/Views/Features/preview-1.cshtml";
            public readonly string preview_2 = "~/Areas/Common/Views/Features/preview-2.cshtml";
            public readonly string preview_3 = "~/Areas/Common/Views/Features/preview-3.cshtml";
            public readonly string preview_4 = "~/Areas/Common/Views/Features/preview-4.cshtml";
            public readonly string releases_css = "~/Areas/Common/Views/Features/releases-css.cshtml";
            public readonly string releases_nav = "~/Areas/Common/Views/Features/releases-nav.cshtml";
            public readonly string releases = "~/Areas/Common/Views/Features/releases.cshtml";
            public readonly string representatives_module = "~/Areas/Common/Views/Features/representatives-module.cshtml";
            public readonly string requirements_css = "~/Areas/Common/Views/Features/requirements-css.cshtml";
            public readonly string requirements = "~/Areas/Common/Views/Features/requirements.cshtml";
            public readonly string students_module = "~/Areas/Common/Views/Features/students-module.cshtml";
            public readonly string travel_module = "~/Areas/Common/Views/Features/travel-module.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_FeaturesController: UCosmic.Www.Mvc.Areas.Common.Controllers.FeaturesController {
        public T4MVC_FeaturesController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Releases(string version) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Releases);
            callInfo.RouteValueDictionary.Add("version", version);
            return callInfo;
        }

        public override System.Web.Mvc.PartialViewResult ReleasesNav() {
            var callInfo = new T4MVC_PartialViewResult(Area, Name, ActionNames.ReleasesNav);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Requirements(string module) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Requirements);
            callInfo.RouteValueDictionary.Add("module", module);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
