// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC.Identity {
    public class SharedController {

        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string _sign_in_form = "~/Areas/Identity/Views/Shared/_sign-in-form.cshtml";
            public readonly string _sign_on_form = "~/Areas/Identity/Views/Shared/_sign-on-form.cshtml";
            public readonly string sign_in = "~/Areas/Identity/Views/Shared/sign-in.cshtml";
            public readonly string sign_on = "~/Areas/Identity/Views/Shared/sign-on.cshtml";
            public readonly string sign_out = "~/Areas/Identity/Views/Shared/sign-out.cshtml";
            static readonly _DisplayTemplates s_DisplayTemplates = new _DisplayTemplates();
            public _DisplayTemplates DisplayTemplates { get { return s_DisplayTemplates; } }
            public partial class _DisplayTemplates{
                public readonly string EmailAddressField = "EmailAddressField";
            }
            static readonly _EditorTemplates s_EditorTemplates = new _EditorTemplates();
            public _EditorTemplates EditorTemplates { get { return s_EditorTemplates; } }
            public partial class _EditorTemplates{
                public readonly string EmailAddressField = "EmailAddressField";
                public readonly string OldSignInForm = "OldSignInForm";
                public readonly string PasswordField = "PasswordField";
                public readonly string RememberMeField = "RememberMeField";
                public readonly string SignInForm = "SignInForm";
                public readonly string SignOnForm = "SignOnForm";
                public readonly string StrengthMeteredPassword = "StrengthMeteredPassword";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
