// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace UCosmic.Www.Mvc.Areas.People.Controllers {
    public partial class PersonNameController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PersonNameController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult GenerateDisplayName() {
            return new T4MVC_JsonResult(Area, Name, ActionNames.GenerateDisplayName);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult AutoCompleteSalutations() {
            return new T4MVC_JsonResult(Area, Name, ActionNames.AutoCompleteSalutations);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult AutoCompleteSuffixes() {
            return new T4MVC_JsonResult(Area, Name, ActionNames.AutoCompleteSuffixes);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PersonNameController Actions { get { return MVC.People.PersonName; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "People";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "PersonName";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "PersonName";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string GenerateDisplayName = "GenerateDisplayName";
            public readonly string AutoCompleteSalutations = "AutoCompleteSalutations";
            public readonly string AutoCompleteSuffixes = "AutoCompleteSuffixes";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string GenerateDisplayName = "GenerateDisplayName";
            public const string AutoCompleteSalutations = "AutoCompleteSalutations";
            public const string AutoCompleteSuffixes = "AutoCompleteSuffixes";
        }


        static readonly ActionParamsClass_GenerateDisplayName s_params_GenerateDisplayName = new ActionParamsClass_GenerateDisplayName();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GenerateDisplayName GenerateDisplayNameParams { get { return s_params_GenerateDisplayName; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GenerateDisplayName {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_AutoCompleteSalutations s_params_AutoCompleteSalutations = new ActionParamsClass_AutoCompleteSalutations();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AutoCompleteSalutations AutoCompleteSalutationsParams { get { return s_params_AutoCompleteSalutations; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AutoCompleteSalutations {
            public readonly string term = "term";
        }
        static readonly ActionParamsClass_AutoCompleteSuffixes s_params_AutoCompleteSuffixes = new ActionParamsClass_AutoCompleteSuffixes();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AutoCompleteSuffixes AutoCompleteSuffixesParams { get { return s_params_AutoCompleteSuffixes; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AutoCompleteSuffixes {
            public readonly string term = "term";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_PersonNameController: UCosmic.Www.Mvc.Areas.People.Controllers.PersonNameController {
        public T4MVC_PersonNameController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.JsonResult GenerateDisplayName(UCosmic.Www.Mvc.Areas.People.Models.GenerateDisplayNameForm model) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.GenerateDisplayName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult AutoCompleteSalutations(string term) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.AutoCompleteSalutations);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult AutoCompleteSuffixes(string term) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.AutoCompleteSuffixes);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
