// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC {
    public class SharedController {

        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string _PjaxLayout = "~/Views/Shared/_PjaxLayout.cshtml";
            public readonly string Error = "~/Views/Shared/Error.cshtml";
            public readonly string feedback_message = "~/Views/Shared/feedback-message.cshtml";
            public readonly string form_submitted_spinner = "~/Views/Shared/form-submitted-spinner.cshtml";
            public readonly string google_analytics_script = "~/Views/Shared/google-analytics-script.cshtml";
            public readonly string google_maps_api_script = "~/Views/Shared/google-maps-api-script.cshtml";
            public readonly string layout = "~/Views/Shared/layout.cshtml";
            public readonly string password_meter = "~/Views/Shared/password-meter.cshtml";
            public readonly string return_url_cancel_link = "~/Views/Shared/return-url-cancel-link.cshtml";
            public readonly string uservoice_link = "~/Views/Shared/uservoice-link.cshtml";
            public readonly string uservoice_widget_script = "~/Views/Shared/uservoice-widget-script.cshtml";
            static readonly _DisplayTemplates s_DisplayTemplates = new _DisplayTemplates();
            public _DisplayTemplates DisplayTemplates { get { return s_DisplayTemplates; } }
            public partial class _DisplayTemplates{
                public readonly string String = "String";
            }
            static readonly _EditorTemplates s_EditorTemplates = new _EditorTemplates();
            public _EditorTemplates EditorTemplates { get { return s_EditorTemplates; } }
            public partial class _EditorTemplates{
                public readonly string Color = "Color";
                public readonly string Date = "Date";
                public readonly string DateTime_Local = "DateTime-Local";
                public readonly string DateTime = "DateTime";
                public readonly string EmailAddress = "EmailAddress";
                public readonly string Month = "Month";
                public readonly string Number = "Number";
                public readonly string PhoneNumber = "PhoneNumber";
                public readonly string Search = "Search";
                public readonly string Time = "Time";
                public readonly string tinymce_full = "tinymce_full";
                public readonly string tinymce_full_compressed = "tinymce_full_compressed";
                public readonly string _Url = "Url";
                public readonly string Week = "Week";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
